### ISSUE TITLE
it cannot work

### ISSUE THREAD

**Issue by YumornZhang** [ethicalhackingplayground/ssrf-king#4]
i have successed installed the plugins in my burp  , but when i passive scan a website ,it seems not work ,what's wrong with me 

Contributor:
	Blake (zoid) (twitter.com/z0idsec)
	
Installation complete.
Payload: http://xbc4r2iu24oykrenb0y4bljiv91zpo.burpcollaborator.net

Calculated your IPs: []

thank you for your help

**Comment by ethicalhackingplayground** [comment]
Thanks for this submission.
Can you please check for the following:

- VPN is disabled
- JDK 11 is installed
- You have burp professional v2020.4 or later

Note:
**It's been tested with Burp Professional v2020.11.2**

I am compiling a version of this plugin for all versions of burp professional very soon. 

Please let me know how you go. 

I will keep this report open until further notice.

Regards,
Blake

**Comment by ethicalhackingplayground** [comment]
Also I just looked at your debug info:

```
Contributor:
Blake (zoid) (twitter.com/z0idsec)

Installation complete.
Payload: http://xbc4r2iu24oykrenb0y4bljiv91zpo.burpcollaborator.net

Calculated your IPs: []
```

It seems your not running the latest version which may not resolve the issue but it's always good practise to keep up to date with the new version. 👍 
Thanks

**Comment by YumornZhang** [comment]
sorry ，i have install jdk 11.07 and burpsuite pro 2020.12.1,but when i scan the website (Basic SSRF against the local server), it still not work
used by ssrd-king 1.12.jar

**Comment by ethicalhackingplayground** [comment]
Thanks for the response. 

Try the following:

- Download the new build there should be a new one I upload today which is still version 1.12 but with a few bug fixes and changes.
- Try JDK 14
Also, could you provide a screenshot & error that your getting so I can see?

Thanks so much!!

Regards,
Blake.

**Comment by ethicalhackingplayground** [comment]
Hey @YumornZhang ,
Other people where facing the same problem that you had. So, I compiled this plugin with JDK 9 which should hopefully fix the compatibility issues.

I am keeping this issue open until further notice,
All the best! let me know how you go.

Regards,
Blake.

**Comment by marz-hunter** [comment]
`java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.a3_.a(Unknown Source)
	at burp.a3_.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.
`
what version of java should i use?

**Comment by ethicalhackingplayground** [comment]
Hi @marz-hunter ,

It should work for all versions now, make sure to downloaded the latest one from the release page.

Let me know how you go :)

Regards,
Blake

**Comment by marz-hunter** [comment]
i downloaded the latest version, but i am using the old version of burp. and I heard that this tool will also be available on Bapp, I'll be waiting for it to install directly from Bapp

**Comment by ethicalhackingplayground** [comment]
Unfortunately at the moment it only works with burp 2020 pro. I will be working on this issue though 👍

**Comment by r89yworld** [comment]
java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.fo5.a(Unknown Source)
	at burp.fo5.<init>(Unknown Source)
	at burp.b91.a(Unknown Source)
	at burp.bb1.lambda$panelLoaded$0(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.


I have the same problem，java version "1.8.0_311"，burpsuite professional v2.1。
Is there a solution!

**Comment by tlfgo** [comment]
Does it work for the burp pro 2021?

**Comment by tlfgo** [comment]
Does it work for the burp pro 2021?
